variables:
  PYTHON_VERSION: "3.14"
  RUFF_VERSION: "0.16.1"
  UV_VERSION: "0.12"
  UV_BASE_LAYER: trixie
  # GitLab CI creates a separate mount point for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

stages:
  - secret_detection
  - audit
  - build
  - test
  - publish

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: secret_detection
  allow_failure: false

audit:
  stage: audit
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$UV_BASE_LAYER
  script:
    - cd $CI_PROJECT_DIR
    - uv audit --preview-features audit

.base_ruff:
  stage: build
  image: ghcr.io/astral-sh/ruff:$RUFF_VERSION-alpine
  interruptible: true
  before_script:
    - cd $CI_PROJECT_DIR
    - ruff --version

.base_uv:
  stage: build
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$UV_BASE_LAYER
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
      policy: pull
  before_script:
    - cd $CI_PROJECT_DIR
    - uv --version
    - uv sync --locked --dev --all-extras
    - uv cache prune --ci

build:
  extends: .base_uv
  stage: build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  script:
    - uv build --no-cache --all-packages

ruff_check:
  extends: .base_ruff
  stage: test
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/code-quality-report.json
  script:
    - ruff check --output-format=gitlab > code-quality-report.json

ruff_format:
  extends: .base_ruff
  stage: test
  script:
    - ruff format --diff

ty:
  extends: .base_uv
  stage: test
  script: uv run ty check -v

publish:
  rules:
    - if: $CI_COMMIT_TAG
  extends: .base_uv
  stage: publish
  script: uv publish --token ${PYPI_TOKEN}
