[project]
name = "dccex"
version = "0.1.2"
description = "Locate and run DCC applications"
readme = "README.md"
authors = [
    { name = "Henrik Wilhelmsen", email = "henrik@hwanimation.tech" }
]
requires-python = ">=3.11"
dependencies = [
    "dccpath>=0.2.1",
]

[project.urls]
Repository = "https://git.hwanimation.tech/hwanimationtech/dccex"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
    "ty>=0.0.65",
]

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = ["packages/*"]
